const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.wrap,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{BackGround: 0},
	{Solid: 0},
	{Floorr: 0},
	{Table: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Character: 0},
	{Sine: 0},
	{HP: 0},
	{Wrap: 0},
	{Task: 0},
	{Bullet: 0},
	{Love: 0},
	{Exit: 0},
	{Blank: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Anchor: 0},
	{Text: 0},
	{HealthMeter: 0},
	{nothin: 0},
	{BG1: 0},
	{Title: 0},
	{Startbtn: 0},
	{abtus: 0},
	{wintxt: 0},
	{rplybtn: 0},
	{plyagn: 0},
	{losetxt: 0},
	{Audio: 0},
	{Note: 0},
	{X: 0},
	{Lives: 0},
	{Score: 0}
];

self.InstanceType = {
	BackGround: class extends self.ISpriteInstance {},
	Floorr: class extends self.ISpriteInstance {},
	Table: class extends self.ISpriteInstance {},
	Character: class extends self.ISpriteInstance {},
	HP: class extends self.ISpriteInstance {},
	Task: class extends self.ISpriteInstance {},
	Love: class extends self.ISpriteInstance {},
	Exit: class extends self.ISpriteInstance {},
	Blank: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	HealthMeter: class extends self.ISpriteInstance {},
	nothin: class extends self.ISpriteInstance {},
	BG1: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	Startbtn: class extends self.ISpriteInstance {},
	abtus: class extends self.ISpriteInstance {},
	wintxt: class extends self.ISpriteInstance {},
	rplybtn: class extends self.ISpriteInstance {},
	plyagn: class extends self.ISpriteInstance {},
	losetxt: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Note: class extends self.ISpriteInstance {},
	X: class extends self.ISpriteInstance {}
}